version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=salesdb;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
    ports:
      - '5000:80'
    # For local dev you may mount source to hot-reload (optional)
    # volumes:
    #   - ./:/app
volumes:
  pgdata:
